### ISSUE TITLE
Error with nested components

### ISSUE THREAD

**Issue by robbiepitts** [tildeio/glimmer#359]
I have a [failing test](https://github.com/robbiepitts/glimmer/commit/f46a8600193474c589971d09de48311fb2ae397f#diff-65b429ee61fd1cb0aa0aa0ceddc81813R95) demonstrating an error I get when trying to render nested angle bracket components:

```
TypeError: Cannot read property 'scan' of null
    at BlockScanner.addStatement (http://localhost:7357/amd/glimmer-runtime.amd.js:6937:54)
    at OpenElement.tagContents (http://localhost:7357/amd/glimmer-runtime.amd.js:8200:25)
    at OpenElement.scan (http://localhost:7357/amd/glimmer-runtime.amd.js:8145:22)
    at BlockScanner.addStatement (http://localhost:7357/amd/glimmer-runtime.amd.js:6937:55)
    at BlockScanner.scan (http://localhost:7357/amd/glimmer-runtime.amd.js:6904:22)
    at buildStatements (http://localhost:7357/amd/glimmer-runtime.amd.js:6885:71)
    at Scanner.scanEntryPoint (http://localhost:7357/amd/glimmer-runtime.amd.js:6850:27)
    at asEntryPoint (http://localhost:7357/amd/glimmer-runtime.amd.js:9104:51)
    at Object.render (http://localhost:7357/amd/glimmer-runtime.amd.js:9117:28)
    at render (http://localhost:7357/amd/glimmer-tests.amd.js:3991:27)
```

I'm able to make the test (and whole suite) pass by checking `scanner.next()` for `null` in `OpenElement#tagContents` but I get the feeling the actual problem is elsewhere. If this is a bug I'd be happy to try to take care of it if I can get a nudge in the right direction.

For context, this is not Ember-related but rather for a little [side project](https://github.com/robbiepitts/sparkles) of mine that uses Glimmer directly.

Thanks for your time!

**Comment by robbiepitts** [comment]
Fixed with #376
